### ISSUE TITLE
Message offset if error while processing messageSet

### ISSUE THREAD

**Issue by gthx** [oleksiyk/kafka#53] opened 2016-04-28 15:16 UTC
How should I handle failure while processing messages?
It seems client/lib uses offset of the last received message and not the latest committed offset.
see https://github.com/oleksiyk/kafka/blob/master/lib/base_consumer.js#L72

Is this a bug or should it be handled by the application.

**Comment by oleksiyk** [comment] 2016-04-28 21:07
Which exactly failure? 

BaseConsumer is just the base class for GroupConsumer and SimpleConsumer which handles fetch requests. When you use Simple Consumer your application must handle offsets positions itself. When you use GroupConsumer you should commit offsets once the message is processed and this committed offset will be used when required (on failure, on rebalance, etc).

**Comment by gthx** [comment] 2016-04-29 06:13
Sorry for incomplete issue.
I'm using GroupConsumer and it seem that GroupConsumer loses messages (skips offsets) if handler fails and new messages are added to the topic.

Attachment contains repro-consumer and repro-producer which are documentation examples with additional exception. Watch for the offset gap in stdout.

[group-consumer-repro.zip](https://github.com/oleksiyk/kafka/files/241840/group-consumer-repro.zip)

**Comment by oleksiyk** [comment] 2016-04-29 07:17
I see. You should be handling `new Error('PROBLEM');` yourself. It is considered a processing error in the application and the library does the only correct step here - logs the error and asks for the next topic message. I just don't think the library should handle application errors:

- if its fatal error (couldn't be skipped) and it should stop the consumer - just stop it and exit. You didn't commit the offset so you will be able to start again from that same message once the problem is resolved;
- if the message could be skipped, then log it and skip it

**Comment by gthx** [comment] 2016-04-29 08:59
I fixed the problem per you suggestion (well not really exiting but restarting the consumer). In the attached repro I use:
```javascript
if (payload === 'PROBLEM') {
      consumer.end().delay(2000).then(function () {
        consumer.init(strategies);
      });
      throw new Error('PROBLEM');
    }
```
I still think that the API is inconsistent (the reason raising the issue). ConsumerGroup user commits offsets explicitly but library internals fast-forwards the offset implicitly.

**Closed** 2016-04-29 15:47 UTC
